"""
tts.py — Text-to-Speech node implementation.

Responsibility: Convert each stop's narration into an MP3 audio file
using OpenAI's gpt-4o-mini-tts model, then package everything into
a tour bundle in backend/storage/.

Output structure:
    backend/storage/{site_id}_{duration_mins}/
        ├── manifest.json
        ├── route.geojson
        ├── stop_1_{stop_id}.mp3
        ├── stop_2_{stop_id}.mp3
        └── ...

Policy compliance:
    OpenAI requires disclosure that TTS audio is AI-generated.
    This disclosure is included in manifest.json.
"""

import os
import json
from pathlib import Path
from dotenv import load_dotenv
from openai import OpenAI

from backend.agents.state import TourState, Stop

load_dotenv()

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# ------------------------------------------------------------------ #
# TTS Configuration
# ------------------------------------------------------------------ #
TTS_MODEL    = "gpt-4o-mini-tts"
TTS_VOICE    = "onyx"
TTS_FORMAT   = "mp3"
STORAGE_DIR  = Path("backend/storage")

TTS_INSTRUCTIONS = """Speak as a passionate and lively heritage tour guide who brings 
ancient history to life with infectious enthusiasm. Your tone should be warm, 
upbeat, and conversational — like sharing an exciting story with a friend, not 
delivering a lecture. Express genuine wonder at the remarkable things you are 
describing. Use natural pauses and vary your pace to keep listeners engaged."""


# ------------------------------------------------------------------ #
# Helpers
# ------------------------------------------------------------------ #
def _make_tour_dir(cache_key: str) -> Path:
    """Create and return the output directory for this tour package."""
    tour_dir = STORAGE_DIR / cache_key
    tour_dir.mkdir(parents=True, exist_ok=True)
    return tour_dir


def _make_stop_filename(index: int, stop: Stop) -> str:
    """Generate a clean filename for a stop's MP3."""
    slug = stop.id.replace("_", "-")
    return f"stop_{index}_{slug}.mp3"


def _narration_to_mp3(narration: str, output_path: Path) -> bool:
    """
    Convert narration text to MP3 using gpt-4o-mini-tts.
    Returns True on success, False on failure.
    """
    try:
        response = client.audio.speech.create(
            model=TTS_MODEL,
            voice=TTS_VOICE,
            input=narration,
            instructions=TTS_INSTRUCTIONS,
            response_format=TTS_FORMAT,
        )
        response.stream_to_file(output_path)
        return True
    except Exception as e:
        print(f"[tts] ERROR generating audio: {e}")
        return False


def _build_manifest(state: TourState, audio_files: list[dict], tour_dir: Path) -> dict:
    """Build the tour manifest JSON."""
    site_name = state.site_id.replace("_", " ").title()
    return {
        "site_id":       state.site_id,
        "site_name":     site_name,
        "duration_mins": state.duration_mins,
        "cache_key":     state.cache_key,
        "stop_count":    len(state.ordered_stops),
        "audio_files":   audio_files,
        "geojson_file":  "route.geojson",
        "ai_disclosure": (
            "This audio tour was generated by artificial intelligence. "
            "The narration voices are AI-generated and not human voices. "
            "All factual content is sourced from Wikipedia."
        ),
    }


# ------------------------------------------------------------------ #
# Main TTS node
# ------------------------------------------------------------------ #
def tts(state: TourState) -> TourState:
    """
    TTS node — converts narration to audio and packages the tour bundle.
    """
    print(f"[tts] Generating audio for {len(state.ordered_stops)} stops.")

    if not state.ordered_stops:
        print(f"[tts] WARNING: No ordered stops to convert.")
        return state

    if not state.final_script:
        print(f"[tts] WARNING: No final script found.")
        return state

    # Create output directory
    tour_dir = _make_tour_dir(state.cache_key)
    print(f"[tts] Output directory: {tour_dir}")

    audio_files = []

    # Convert each stop's narration to MP3
    for i, stop in enumerate(state.ordered_stops, 1):
        if not stop.narration:
            print(f"[tts] WARNING: No narration for {stop.name} — skipping.")
            continue

        filename    = _make_stop_filename(i, stop)
        output_path = tour_dir / filename

        print(f"[tts] Generating audio for stop {i}: {stop.name}...")
        success = _narration_to_mp3(stop.narration, output_path)

        if success:
            size_kb = output_path.stat().st_size // 1024
            print(f"[tts] ✓ {filename} ({size_kb} KB)")
            audio_files.append({
                "stop_number": i,
                "stop_id":     stop.id,
                "stop_name":   stop.name,
                "filename":    filename,
                "size_kb":     size_kb,
            })
        else:
            print(f"[tts] ✗ Failed to generate audio for {stop.name}")

    # Save GeoJSON route
    geojson_path = tour_dir / "route.geojson"
    with open(geojson_path, "w", encoding="utf-8") as f:
        json.dump(state.geojson_route, f, indent=2, ensure_ascii=False)
    print(f"[tts] ✓ route.geojson saved.")

    # Save manifest
    manifest      = _build_manifest(state, audio_files, tour_dir)
    manifest_path = tour_dir / "manifest.json"
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
    print(f"[tts] ✓ manifest.json saved.")

    print(f"[tts] ✓ Tour package complete: {tour_dir}")
    return state
